name: Build and Publish Vaultwarden

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - uses: actions/cache@v4
      with:
        path: C:\vcpkg\installed
        key: ${{ runner.os }}-vcpkg-installed-${{ env.OS_VER }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-installed-${{ env.OS_VER }}-
          ${{ runner.os }}-vcpkg-installed-
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install OpenSSL and libpq
      run: |
        vcpkg install --triplet x64-windows-static-md openssl libpq
      env:
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Install MySQL Server
      run: |
        choco install mysql --version=9.2.0

    - name: Set environment variables
      run: |
        echo "MYSQLCLIENT_VERSION=9.2" >> $GITHUB_ENV
        echo "MYSQLCLIENT_LIB_DIR=C:\\Program Files\\MySQL\\MySQL Server 9.2\\lib" >> $GITHUB_ENV
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Build Vaultwarden
      run: |
        git clone https://github.com/dani-garcia/vaultwarden.git
        cd vaultwarden
        git checkout 1.34.1
        cargo build --features sqlite,mysql,postgresql --release
      env:
        MYSQLCLIENT_VERSION: ${{ env.MYSQLCLIENT_VERSION }}
        MYSQLCLIENT_LIB_DIR: ${{ env.MYSQLCLIENT_LIB_DIR }}
        OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
        LIBPQ_DIR: ${{ env.LIBPQ_DIR }}

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Vaultwarden
        path: target/release/vaultwarden.exe
