name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable


    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg integrate install

    - name: Install OpenSSL
      run: |
        ./vcpkg install openssl:x64-windows

    - name: Install libpq
      run: |
        ./vcpkg install libpq:x64-windows

    - name: Install MySQL Server
      run: |
        choco install mysql --version=9.2.0

    - name: Set environment variables
      run: |
        echo "VCPKG_ROOT=$(pwd)\\vcpkg" >> $GITHUB_ENV
        echo "OPENSSL_DIR=$(pwd)\\vcpkg\\installed\\x64-windows" >> $GITHUB_ENV
        echo "LIBPQ_DIR=$(pwd)\\vcpkg\\installed\\x64-windows" >> $GITHUB_ENV
        echo "MYSQLCLIENT_VERSION=9.2" >> $GITHUB_ENV
        echo "MYSQLCLIENT_LIB_DIR=C:\\Program Files\\MySQL\\MySQL Server 9.2\\lib" >> $GITHUB_ENV

    - name: Build Vaultwarden
      run: |
        git clone https://github.com/dani-garcia/vaultwarden.git
        cd vaultwarden
        git checkout 1.34.1
        cargo build --features sqlite,mysql,postgresql --release
      env:
        MYSQLCLIENT_VERSION: ${{ env.MYSQLCLIENT_VERSION }}
        MYSQLCLIENT_LIB_DIR: ${{ env.MYSQLCLIENT_LIB_DIR }}
        OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
        LIBPQ_DIR: ${{ env.LIBPQ_DIR }}

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: Vaultwarden
        path: target/release/vaultwarden.exe
